# the code you will be writting here will be production grade...
# first write in local_ai.py to write development code then turn it into function based /class based to exchange data in json format.
# write it organizely and cleanly and with success and error message
